# Generated by Django 4.2.9 on 2024-01-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_client_date_of_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
